* What makes for a good mutation operator?

** background

From [https://arxiv.org/pdf/1203.3099.pdf]:

#+BEGIN_QUOTE
Mutation prevents the algorithm to be trapped in a local minimum. Mutation plays
the role of recovering the lost genetic materials as well as for randomly
disturbing genetic information. It is an insurance policy against the
irreversible loss of genetic material. Mutation has traditionally considered as
a simple search operator. If crossover is supposed to exploit the current
solution to find better ones, mutation is supposed to help for the exploration
of the whole search space. Mutation is viewed as a background operator to
maintain genetic diversity in the population. It introduces new genetic
structures in the population by randomly modifying some of its building blocks.
Mutation helps escape from local minima’s trap and maintains diversity in the
population. It also keeps the gene pool well stocked, and thus ensuring
ergodicity. 
#+END_QUOTE


** conjectures

*** they should form a cyclic group under concatenation
*** they should cover the genotype space as well as possible
